### ISSUE TITLE
Can't change Local directory location

### ISSUE THREAD

**Issue by kaitwalla** [pantheon-systems/localdev-issues#119]
10.15.7, LocalDev 1.2.0.1084

Whenever I try to change the Local directory for a new environment, it always throws a JavaScript error:

```Uncaught Exception:
Error: Failed to serialize arguments
    at Object.n.send (electron/js2c/browser_init.js:165:413)
    at Object.b.send (electron/js2c/browser_init.js:161:2471)
    at IpcMainImpl.<anonymous> (/Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/main.js:1:7241)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9469)
    at Object.emit (events.js:315:20)
```

To reproduce:

Select any site not already cloned locally. Click "Change Location," then "Change Path" in the modal that pops up. Though the file browser pops up, selecting a folder makes no changes.

**Comment by matthewwoodard** [comment]
+1 - this is happening to me as well. Any fixes? Workarounds?

**Comment by nicholausrowe** [comment]
I'm having the same issue. Would love a fix or workaround.
