### ISSUE TITLE
PHP 7.3 in pantheon.yml breaks sites

### ISSUE THREAD

**Issue by mlangone** [pantheon-systems/localdev-issues#12]
If this is the incorrect place please lmk and I will close this immediately. I am trying to pull down and the application keeps erroring out.

```
{"level":"verbose","message":"Response recieved: [].","timestamp":"2019-05-06T18:55:48.836Z"}
{"level":"verbose","message":"Response recieved: [{\"archived\":false,\"invited_by_id\":\"REDACTED\",\"role\":\"team_member\",\"id\":\"REDACTED\",\"key\":\"REDACTED\",\"site_id\":\"REDACTED\",\"user_id\":\"REDACTED\",\"site\":{\"user_in_charge_id\":\"REDACTED\",\"product\":{\"id\":\"5758ea6a-bfda-4d56-bc0c-38584ec1a448\",\"longname\":\"WordPress\"},\"service_level\":\"free\",\"user_in_charge\":{\"profile\":{\"seens\":{\"partner-program\":true,\"skip-cms-installation\":{\"c6c47010-2f37-495e-a6f1-47c05e4009ab\":true}},\"web_services_business\":null,\"full_name\":\"Mike Langone\",\"firstname\":\"Mike\",\"lastname\":\"Langone\",\"pda_campaign\":null,\"modified\":1555521151,\"experiments\":{\"welcome_video\":\"shown\"},\"initial_identity_name\":null,\"registration_context\":\"new_developer\",\"maxdevsites\":2,\"verify\":\"0983814ce95e7bdaa8b6f0f19f2a7f82\",\"job_function\":\"\",\"organization\":\"\",\"guilty_of_abuse\":null,\"initial_identity_strategy\":null},\"id\":\"84679d8e-454f-4076-bef0-c6c041a47ca0\",\"email\":\"mike@onlineimage.com\"},\"upstream_updates_by_environment\":{\"remote_head\":\"43b2a6343b867624fac1bb9488d5dd397d9d9ee6\",\"ahead\":1,\"remote_branch\":\"refs/remotes/origin/master\",\"live\":{},\"dev\":{\"has_code\":true,\"is_up_to_date_with_upstream\":true},\"behind\":0,\"has_code\":true,\"test\":{\"has_code\":true,\"is_up_to_date_with_upstream\":true},\"has_remote_head\":true,\"remote_url\":\"https://github.com/pantheon-systems/WordPress\"},\"preferred_availability_zone\":\"us-central1-b\",\"framework\":\"wordpress\",\"upstream\":{\"url\":\"https://github.com/pantheon-systems/WordPress\",\"product_id\":\"e8fe8550-1ab9-4964-8838-2b9abdccf4bf\",\"branch\":\"master\"},\"owner\":\"84679d8e-454f-4076-bef0-c6c041a47ca0\",\"holder\":{\"profile\":{\"seens\":{\"partner-program\":true,\"skip-cms-installation\":{\"c6c47010-2f37-495e-a6f1-47c05e4009ab\":true}},\"web_services_business\":null,\"full_name\":\"Mike Langone\",\"firstname\":\"Mike\",\"lastname\":\"Langone\",\"pda_campaign\":null,\"modified\":1555521151,\"experiments\":{\"welcome_video\":\"shown\"},\"initial_identity_name\":null,\"registration_context\":\"new_developer\",\"maxdevsites\":2,\"verify\":\"0983814ce95e7bdaa8b6f0f19f2a7f82\",\"job_function\":\"\",\"organization\":\"\",\"guilty_of_abuse\":null,\"initial_identity_strategy\":null},\"id\":\"REDACTED\",\"email\":\"mike@onlineimage.com\"},\"id\":\"REDACTED\",\"preferred_zone\":\"us-central1\",\"product_id\":\"5758ea6a-bfda-4d56-bc0c-38584ec1a448\",\"created_by_user_id\":\"REDACTED\",\"holder_id\":\"84679d8e-454f-4076-bef0-c6c041a47ca0\",\"name\":\"aesmain\",\"created\":1555522625,\"holder_type\":\"user\",\"php_version\":\"55\",\"site_routing_to_legacy_edge\":false,\"allow_cacheserver\":true,\"attributes\":{\"m3_ui\":true,\"label\":\"AESMain\"},\"plan_name\":\"Sandbox\",\"last_code_push\":{\"timestamp\":\"2019-05-06T16:39:41\",\"user_uuid\":null}}}].","timestamp":"2019-05-06T18:55:48.892Z"}
{"level":"debug","message":"Engine is down with error Error","timestamp":"2019-05-06T18:55:52.475Z"}
{"level":"debug","message":"Engine is down with error Error","timestamp":"2019-05-06T18:55:57.472Z"}
{"level":"warn","message":"Docker has started but we are waiting for a connection","timestamp":"2019-05-06T18:56:00.787Z"}
{"level":"warn","message":"You should be good to go momentarily!","timestamp":"2019-05-06T18:56:00.787Z"}
{"level":"debug","message":"Engine is down with error Error","timestamp":"2019-05-06T18:56:02.475Z"}
{"level":"debug","message":"Engine is down with error Error","timestamp":"2019-05-06T18:56:07.472Z"}
{"level":"debug","message":"Engine is down with error Error","timestamp":"2019-05-06T18:56:12.476Z"}
{"level":"debug","message":"Engine is down with error Error","timestamp":"2019-05-06T18:56:17.471Z"}
{"level":"debug","message":"Engine is down with error Error","timestamp":"2019-05-06T18:56:22.476Z"}
{"level":"warn","message":"Docker has started but we are waiting for a connection","timestamp":"2019-05-06T18:56:24.794Z"}
{"level":"warn","message":"You should be good to go momentarily!","timestamp":"2019-05-06T18:56:24.794Z"}
{"level":"debug","message":"Engine is down with error Error","timestamp":"2019-05-06T18:56:27.472Z"}
{"level":"debug","message":"Engine is down with error Error","timestamp":"2019-05-06T18:56:32.473Z"}
{"level":"debug","message":"Engine is down with error Error","timestamp":"2019-05-06T18:56:37.477Z"}
{"level":"debug","message":"Engine is down with error Error","timestamp":"2019-05-06T18:56:42.475Z"}
{"level":"debug","message":"Engine is down with error Error","timestamp":"2019-05-06T18:56:47.474Z"}
{"level":"warn","message":"Docker has started but we are waiting for a connection","timestamp":"2019-05-06T18:56:49.800Z"}
{"level":"warn","message":"You should be good to go momentarily!","timestamp":"2019-05-06T18:56:49.801Z"}
{"level":"debug","message":"Emitting event message","timestamp":"2019-05-06T18:56:49.808Z"}
{"level":"debug","message":"Event message has 1 listeners","timestamp":"2019-05-06T18:56:49.808Z"}
{"context":"localdev","message":"Error: Error: spawn /Applications/Docker.app/Contents/Resources/bin/docker ENOENT","stack":"Error: Error: Error: spawn /Applications/Docker.app/Contents/Resources/bin/docker ENOENT\n    at shell.sh.retry.then.catch.err (/Applications/Localdev.app/Contents/Resources/app.asar/node_modules/lando/lib/daemon.js:113:19)\nFrom previous event:\n    at isUp.then.isUp (/Applications/Localdev.app/Contents/Resources/app.asar/node_modules/lando/lib/daemon.js:112:17)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:109:7)\nFrom previous event:\n    at self.events.emit.then (/Applications/Localdev.app/Contents/Resources/app.asar/node_modules/lando/lib/daemon.js:98:59)\nFrom previous event:\n    at LandoDaemon.up (/Applications/Localdev.app/Contents/Resources/app.asar/node_modules/lando/lib/daemon.js:93:6)\n    at Object.exports.eventWrapper (/Applications/Localdev.app/Contents/Resources/app.asar/node_modules/lando/lib/router.js:24:68)\n    at Engine.engineCmd (/Applications/Localdev.app/Contents/Resources/app.asar/node_modules/lando/lib/engine.js:17:104)\n    at Engine.list (/Applications/Localdev.app/Contents/Resources/app.asar/node_modules/lando/lib/engine.js:223:17)\n    at run (/Applications/Localdev.app/Contents/Resources/app.asar/node_modules/lando/plugins/lando-core/tasks/poweroff.js:14:27)\n    at file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:1008813\n    at <anonymous>\nFrom previous event:\n    at Object.T [as stopAll] (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:1008790)\n    at n.totalDestruction (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:319987)\n    at n.e (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:44830)\n    at n.t.$emit (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:100986)\n    at n.hide (/Applications/Localdev.app/Contents/Resources/app.asar/node_modules/bootstrap-vue/dist/bootstrap-vue.common.js:10298:14)\n    at click (/Applications/Localdev.app/Contents/Resources/app.asar/node_modules/bootstrap-vue/dist/bootstrap-vue.common.js:9972:17)\n    at e (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:44802)\n    at HTMLButtonElement.t._withTask.t._withTask (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:44156)","type":"error","level":"error","timestamp":"2019-05-06T18:56:49.809Z"}
{"level":"debug","message":"Logging metrics data {\"context\":\"local\",\"devMode\":false,\"nodeVersion\":\"v7.9.0\",\"mode\":\"gui\",\"os\":{\"type\":\"Darwin\",\"platform\":\"darwin\",\"release\":\"18.5.0\",\"arch\":\"x64\"},\"product\":\"localdev\",\"version\":\"0.4.0\",\"message\":\"Error: Error: spawn /Applications/Docker.app/Contents/Resources/bin/docker ENOENT\",\"action\":\"error\",\"created\":\"2019-05-06T18:56:49.809Z\"}","timestamp":"2019-05-06T18:56:49.809Z"}
{"level":"debug","message":"Engine is down with error Error","timestamp":"2019-05-06T18:56:52.475Z"}

```

**Comment by mlangone** [comment]
I was able to solve the issue on my own and here is what I found.

By upgrading my browser based multidev environment to php 7.3 it broke things developer console errors showed "pantheon-appserver 7.3-2 is not found".  I went into my site specific pantheon.yml file and changed the php version back to 7.2 that allowed me to successfully pull and get localdev up and running again.

**Comment by joshkoenig** [comment]
Makes sense. We're looking forward to a fix for this soon. Will let you know once a release is pushed out, hopefully before the end of the month.

**Comment by pirog** [comment]
There is now an upstream Lando image for 7.3 so it should now be possible to boot up a site on 7.3. This does not require an update to PLD code as long as you are already on the most recent version.
