### ISSUE TITLE
	pulling database from dev errored with: ERROR 1451 (23000) at line 1: Cannot delete or update a parent row: a foreign key constraint fails

### ISSUE THREAD

**Issue by wernerglinka** [pantheon-systems/localdev-issues#77]
Very curious??? I pushed a local WP site to dev and then immediately pulled it. The pull fails with 

**pulling database from dev errored with: ERROR 1451 (23000) at line 1: Cannot delete or update a parent row: a foreign key constraint fails**

Does anybody has seen this?  Any idea what is going on with this?

**Comment by wernerglinka** [comment]
This is what I get in the error log:

```
{"level":"error","message":"database reported as unhealthy.","label":"fdap01","timestamp":"2020-07-14T00:59:10.355Z"}
{"message":"","stack":"Error\n    at file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:168322\nFrom previous event:\n    at n.f [as _captureStackTrace] (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:695018)\n    at new c (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:745635)\n    at l (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:745840)\n    at e.reduce (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:747889)\n    at Function.t.mapSeries (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:709127)\n    at Object.e.run (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:890069)\n    at n (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:243403)\n    at file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:889672","__stackCleaned__":true,"level":"error","label":"fdap01","timestamp":"2020-07-14T02:35:08.049Z"}
{"level":"error","message":"Starting pld-fdap01_appserver_nginx_1 ... \r\n\u001b[1A\u001b[2K\rStarting pld-fdap01_appserver_nginx_1 ... \u001b[31merror\u001b[0m\r\u001b[1B\nERROR: for pld-fdap01_appserver_nginx_1  Cannot start service appserver_nginx: container is marked for removal and cannot be started\n\nERROR: for appserver_nginx  Cannot start service appserver_nginx: container is marked for removal and cannot be started\nEncountered errors while bringing up the project.\n","label":"fdap01","timestamp":"2020-07-14T02:35:10.017Z"}
{"level":"warn","message":"problem pulling database from dev!","label":"fdap01","timestamp":"2020-07-14T02:35:50.736Z"}
{"level":"error","message":"pulling database from dev errored with: mysqldump: Got errno 32 on write\n","label":"fdap01","timestamp":"2020-07-14T02:35:50.738Z"}
{"level":"warn","message":"problem pulling database from dev!","label":"fdap01","timestamp":"2020-07-14T02:51:45.137Z"}
{"level":"error","message":"pulling database from dev errored with: ERROR 1451 (23000) at line 1: Cannot delete or update a parent row: a foreign key constraint fails\n","label":"fdap01","timestamp":"2020-07-14T02:51:45.138Z"}
{"level":"warn","message":"problem pulling database from dev!","label":"fdap01","timestamp":"2020-07-14T15:26:10.022Z"}
{"level":"error","message":"pulling database from dev errored with: ERROR 1451 (23000) at line 1: Cannot delete or update a parent row: a foreign key constraint fails\n","label":"fdap01","timestamp":"2020-07-14T15:26:10.023Z"}
{"level":"warn","message":"problem pulling database from dev!","label":"fdap01","timestamp":"2020-07-14T15:31:37.052Z"}
{"level":"error","message":"pulling database from dev errored with: ERROR 1451 (23000) at line 1: Cannot delete or update a parent row: a foreign key constraint fails\n","label":"fdap01","timestamp":"2020-07-14T15:31:37.053Z"}
{"level":"warn","message":"problem pulling database from dev!","label":"fdap01","timestamp":"2020-07-14T15:34:38.338Z"}
{"level":"error","message":"pulling database from dev errored with: ERROR 1451 (23000) at line 1: Cannot delete or update a parent row: a foreign key constraint fails\n","label":"fdap01","timestamp":"2020-07-14T15:34:38.339Z"}

```

**Comment by wernerglinka** [comment]
For anyone who is seeing this. This must have been a result of the last Localdev upgrade. Even though the app seems to update the local instance I got this working again by **Force Remove** and pulling it again to local. 

Related to https://github.com/lando/lando/issues/2391
