### ISSUE TITLE
Localdev is no longer able to detect a WordPress installation with Composer.

### ISSUE THREAD

**Issue by cameroncondry** [pantheon-systems/localdev-issues#80]
I currently have an installation on Patheon that uses the web docroot and WordPress being installed by composer. This puts the WordPress files in "web/wp/", which is now causing Localdev to throw the following error:

```
Pulling your database... This miiiiight take a minute
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Doing the ole post-migration search-replace on WordPress...
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Error: This does not seem to be a WordPress installation.
Pass --path=`path/to/wordpress` or run `wp core download`.
```

This issue only started happening recently, since my team has been able to use Localdev without issue until we tried to rebuild one of the environments today. The site is created as an empty wordpress site so that Pantheon knows how to work with our installation: " Upstream | https://github.com/pantheon-systems/empty-wp.git".

Is there any means to get around this issue? It looks like we could pass a flag to point to the wordpress installation, but I don't see a way to pass commands in the Localdev interface. This has completely stopped our environments, and I am ok with any sort of stop-gap measure to make Localdev work.

Thank you for any help you can provide.

**Comment by cameroncondry** [comment]
I just tried updating to the Edge branch of Localdev, and that does get me past the WordPress check, but for some reason Localdev is now trying to fire up the whole WordPress installation.

```
PHP Fatal error:  Uncaught Error: Call to undefined function App\sage() in /app/web/app/mu-plugins/cm-includes/cm-blade-cache.php:62
Stack trace:
#0 /app/web/wp/wp-includes/class-wp-hook.php(287): CascadeMedia\WordPress\BladeCache\ensure_blade_cache_exists('')
#1 /app/web/wp/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /app/web/wp/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /app/web/wp/wp-settings.php(540): do_action('init')
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1237): require('/app/web/wp/wp-...')
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1158): WP_CLI\Runner->load_wordpress()
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstra in /app/web/app/mu-plugins/cm-includes/cm-blade-cache.php on line 62
Fatal error: Uncaught Error: Call to undefined function App\sage() in /app/web/app/mu-plugins/cm-includes/cm-blade-cache.php:62
Stack trace:
#0 /app/web/wp/wp-includes/class-wp-hook.php(287): CascadeMedia\WordPress\BladeCache\ensure_blade_cache_exists('')
#1 /app/web/wp/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /app/web/wp/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /app/web/wp/wp-settings.php(540): do_action('init')
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1237): require('/app/web/wp/wp-...')
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1158): WP_CLI\Runner->load_wordpress()
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstra in /app/web/app/mu-plugins/cm-includes/cm-blade-cache.php on line 62
```

**Comment by cameroncondry** [comment]
I've resolved the issue. It looks like Localdev now requires the ability to use WP-CLI before it will pull the code locally. Previously it did not require this check, or it did not completely bail if WP-CLI didn't connect.

I don't think Localdev should require WP-CLI, especially since managing WordPress with Composer has become much more popular. Maybe there should be some way to pass in arguments or a feature on the interface that you can help Localdev know where WP is installed.

I'll close this issue since I've found a resolution. Thanks for your time!
