### ISSUE TITLE
Get "Error: mkdir: cannot create directory" when spinning up a site

### ISSUE THREAD

**Issue by bmarshall511** [pantheon-systems/localdev-issues#86]
Just installed Localdev and attempt to spin up a site, by every time I do, it ends up canceling with an error:

```
\rStarting localdevproxyhyperion5004radagastedition_proxy_1 ... done\r","stack":"Error: mkdir: cannot create directory '/app/./wp-content/uploads': File exists\n\n    at file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:17:1117219\n    at processTicksAndRejections (internal/process/task_queues.js:86:5)\nFrom previous event:\n    at file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:17:1117070\n    at i.l (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:713193)\n    at i.n (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:759494)\n    at n._settlePromiseFromHandler (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:732606)\n    at n._settlePromise (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:733174)\n    at n._settlePromise0 (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:734104)\n    at n._settlePromises (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:735457)\n    at i (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:686955)\n    at n (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:686894)\n    at r._drainQueues (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:688096)\n    at drainQueues (file:///Applications/Localdev.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:686828)
```

**Comment by pirog** [comment]
@bmarshall511 i would try the latest version of Localdev. If that does not work then please feel free to reopen this.
